name: PlotMasterPlugin
authors: [Double0negative, MCSG]
version: 0.0.1
main: bukkit.org.mcsg.plotmaster.PlotMasterPlugin
soft-depends: [GroovyRuntime]


commands:
    plot:
        description: Survival Games Command
        usage: /sg <command> <args>
        aliases: [pl, p, plots, pm, plotmaster]
